//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : JuhaszAdamFrogger
//  @ File Name : Car.h
//  @ Date : 2015.11.14.
//  @ Author : Juhász Ádám
//
//


#if !defined(_CAR_H)
#define _CAR_H

#include "Entity.h"
#include "DirectionEnum.h"

class Car : public Entity
{
private:
    int speed;
    DirectionEnum direction;
public:
    Car(int x, int y, int speed, int color, char symbol, DirectionEnum direction);
    void tick();
    void draw();
    bool collidesWithFrog();
};

#endif  //_CAR_H
