//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : JuhaszAdamFrogger
//  @ File Name : Car.cpp
//  @ Date : 2015.11.14.
//  @ Author : Juhász Ádám
//
//

#include "Car.h"
#include "MyConsole.h"
#include "Playground.h"
#include <windows.h>

Car::Car(int x, int y, int speed, int color, char symbol, DirectionEnum direction)
{
    position.setX(x);
    position.setY(y);
    this->speed = speed;
    this->color = color;
    this->symbol = symbol;
    this->direction = direction;
}

void Car::draw()
{
    Playground::getInstance()->console->fillArea(
        position.getX(),
        position.getY(),
        position.getX()+4,
        position.getY()+2,
        color,
        symbol
    );
}

void Car::tick()
{
    if(Playground::getInstance()->round % (100-speed) == 0)
    {
        switch(direction)
        {
        case Left:
            position.setCoordinates(position.getX()-1, position.getY());
            if(position.getX()<2)
            {
                position.setX(74);
            }
            break;
        case Right:
            position.setCoordinates(position.getX()+1, position.getY());
            if(position.getX()>74)
            {
                position.setX(2);
            }
            break;
        }
    }

    if (collidesWithFrog())
    {
        Playground::getInstance()->active = false;
    }
}

bool Car::collidesWithFrog()
{
    int fx = Playground::getInstance()->frog.position.getX();
    int fy = Playground::getInstance()->frog.position.getY();
    int cx = position.getX();
    int cy = position.getY();

    // Todo: Overhead, mert kettesével lépünk
    for (int i=0; i<4; i++)
    {
        for (int j=0; j<2; j++)
        {
            if(cx+i == fx+j && cy == fy)
            {
                return true;
            }
            if(cx+i == fx+j && cy == fy+1)
            {
                return true;
            }
            if(cx+i == fx+j && cy+1 == fy)
            {
                return true;
            }
            if(cx+i == fx+j && cy+1 == fy+1)
            {
                return true;
            }
        }
    }

    return false;
}
