//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : JuhaszAdamFrogger
//  @ File Name : Console.h
//  @ Date : 2015.11.14.
//  @ Author : Juhász Ádám
//
//


#if !defined(_CONSOLE_H)
#define _CONSOLE_H


class Console
{
private:
    int width;
    int height;
public:
    Console();

    void setSize(int w, int h);

    int getWidth()
    {
        return width;
    }

    int getHeight()
    {
        return height;
    }

    void clearScreen();
    void drawBuffer();
    void setPosition(int x, int y);
    void draw(int x, int y, int color, char symbol);
    void fillArea(int ax, int ay, int bx, int by, int color, char symbol);
};

#endif  //_CONSOLE_H
