//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : JuhaszAdamFrogger
//  @ File Name : Coordinate.h
//  @ Date : 2015.11.14.
//  @ Author : Juhász Ádám
//
//


#if !defined(_COORDINATE_H)
#define _COORDINATE_H


class Coordinate
{
public:
    Coordinate(int x, int y);
    Coordinate();
    bool collidesWith(Coordinate other);
    int getX();
    int getY();
    void setX(int x);
    void setY(int y);
    void setCoordinates(int x, int y);

private:
    int x;
    int y;
};

#endif  //_COORDINATE_H
