//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : JuhaszAdamFrogger
//  @ File Name : DirectionEnum.h
//  @ Date : 2015.11.14.
//  @ Author : Juhász Ádám
//
//


#if !defined(_DIRECTIONENUM_H)
#define _DIRECTIONENUM_H

enum DirectionEnum {
	Up,
	Right,
	Down,
	Left
};

#endif  //_DIRECTIONENUM_H
