//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : JuhaszAdamFrogger
//  @ File Name : Entity.h
//  @ Date : 2015.11.14.
//  @ Author : Juhász Ádám
//
//


#if !defined(_ENTITY_H)
#define _ENTITY_H

#include "Coordinate.h"

class Entity
{
public:
    virtual void tick() = 0;
    Coordinate position;
    int color;
    char symbol;
};

#endif  //_ENTITY_H
