//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : JuhaszAdamFrogger
//  @ File Name : Frog.cpp
//  @ Date : 2015.11.14.
//  @ Author : Juhász Ádám
//
//

#include "Frog.h"
#include "Playground.h"
#include "MyConsole.h"

Frog::Frog()
{
    position.setCoordinates(38,15);
    color = FCIM|BCR;
    symbol = '@';
}

void Frog::move(DirectionEnum direction)
{
    switch(direction)
    {
    case Up:
        position.setY(position.getY()-2);
        break;
    case Down:
        position.setY(position.getY()+2);
        break;
    case Right:
        position.setX(position.getX()+2);
        break;
    case Left:
        position.setX(position.getX()-2);
        break;
    }

    if ((position.getX()+2)>Playground::getInstance()->console->getWidth()-4)
        position.setX(Playground::getInstance()->console->getWidth()-4);
    if (position.getX()<2)
        position.setX(2);

    if ((position.getY()+2)>Playground::getInstance()->console->getHeight()-10)
        position.setY(Playground::getInstance()->console->getHeight()-10);

    if (position.getY() <= 4){
        Playground::getInstance()->active=false;
        Playground::getInstance()->victory=true;
    }
}

void Frog::tick()
{
}

void Frog::render()
{
    Playground::getInstance()->console->fillArea(
        position.getX(),
        position.getY(),
        position.getX()+2,
        position.getY()+2,
        color,
        symbol
    );
}
