//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : JuhaszAdamFrogger
//  @ File Name : Playground.h
//  @ Date : 2015.11.14.
//  @ Author : Juhász Ádám
//
//

#if !defined(_PLAYGROUND_H)
#define _PLAYGROUND_H

#include "Car.h"
#include "Frog.h"
#include "Console.h"
#include <cstddef>
#include <vector>
#include <time.h>
#include <stdlib.h>

using namespace std;
class Playground
{
private:
    Playground();
    static Playground* instance;
    void drawWorld();

public:
    Console *console;
    int round;
    bool active;
    bool victory;

    static Playground* getInstance()
    {
        if (instance == NULL)
        {
            instance = new Playground();
        }

        return instance;
    }

    void init();
    void tick();
    vector<Car> carList;
    Frog frog;
};
#endif  //_PLAYGROUND_H
